apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    tier: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      tier: database
  template:
    metadata:
      labels:
        tier: database
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: mysql
        image: bookstore-db:1.0.0
        env:
        - name: MYSQL_DATABASE
          value: "bookstore"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstore-secrets
              key: MYSQL_ROOT_PASSWORD
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: tmp
          mountPath: /tmp
        - name: run
          mountPath: /var/run/mysqld
      volumes:
      - name: tmp
        emptyDir: {}
      - name: run
        emptyDir: {}
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pv-claim