apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bookstore-pipeline
spec:
  workspaces:
    - name: shared-data
  params:
    - name: git-url
      type: string
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: Task # Looking for the Task we installed in your namespace
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: "main"

    - name: build-images
      runAfter: [fetch-repository]
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: manifest-dir
          workspace: shared-data
      params:
        - name: SCRIPT
          value: |
            oc start-build bookstore-db-build --from-dir=$(workspaces.manifest-dir.path)/database --follow
            oc start-build bookstore-backend-build --from-dir=$(workspaces.manifest-dir.path)/backend --follow
            oc start-build bookstore-frontend-build --from-dir=$(workspaces.manifest-dir.path)/frontend --follow

    - name: scan-backend
      runAfter: [build-images]
      taskRef:
        name: trivy-scanner
        kind: Task
      params:
        - name: IMAGE_PATH
          value: "bookstore-backend:1.0.0"
        - name: ARGS
          value: ["image", "--severity", "CRITICAL", "--exit-code", "1", "--ignore-unfixed"]

    - name: deploy-kustomize
      runAfter: [scan-backend]
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: manifest-dir
          workspace: shared-data
      params:
        - name: SCRIPT
          value: |
            # Ensure this path matches your repo structure
            cd $(workspaces.manifest-dir.path)/openshift/base
            oc apply -k .