apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: bookstore-pipeline
spec:
  workspaces:
    - name: shared-data
  params:
    - name: git-url
      type: string
  tasks:
    # 1. FETCH REPOSITORY
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: Task
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: "main"

    # 2. SETUP INFRASTRUCTURE: Create BuildConfigs, Secrets, and Services FIRST
    - name: setup-infra
      runAfter: [fetch-repository]
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: manifest-dir
          workspace: shared-data
      params:
        - name: SCRIPT
          value: |
            cd $(workspaces.manifest-dir.path)/openshift/base
            echo "Creating BuildConfigs and infrastructure..."
            oc apply -k .

    # 3. BUILD IMAGES: Now the BuildConfigs exist, we can start them
    - name: build-images
      runAfter: [setup-infra]
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: manifest-dir
          workspace: shared-data
      params:
        - name: SCRIPT
          value: |
            echo "Starting builds..."
            oc start-build bookstore-db-build --from-dir=$(workspaces.manifest-dir.path)/database --follow
            oc start-build bookstore-backend-build --from-dir=$(workspaces.manifest-dir.path)/backend --follow
            oc start-build bookstore-frontend-build --from-dir=$(workspaces.manifest-dir.path)/frontend --follow

    # 4. SCAN BACKEND
    - name: scan-backend
      runAfter: [build-images]
      taskRef:
        name: trivy-scanner
        kind: Task
      workspaces:
        - name: manifest-dir
          workspace: shared-data
      params:
        - name: IMAGE_PATH
          value: "image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/bookstore-backend:1.0.0"
        - name: ARGS
          value: ["image", "--severity", "CRITICAL", "--exit-code", "1", "--ignore-unfixed", "--clear-cache"]

    # 5. VERIFY DEPLOYMENT: Ensure the pods actually start with the new images
    - name: verify-deployment
      runAfter: [scan-backend]
      taskRef:
        name: openshift-client
        kind: Task
      params:
        - name: SCRIPT
          value: |
            echo "Verifying rollout..."
            oc rollout status deployment/backend --timeout=120s
            oc rollout status deployment/frontend --timeout=120s
            echo "--- PIPELINE COMPLETE ---"
            echo "URL: http://$(oc get route bookstore-frontend -o jsonpath='{.spec.host}')"